#include "game.h"
#include "graphics.h"
#include "input.h"
#include "audio.h"
#include "save.h"

GameState g_game;

// Handcrafted Room Blueprints (20x15 metatiles)
static const MetatileId s_room_camp_blueprint[ROOM_HEIGHT][ROOM_WIDTH] = {
    {META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_DOOR_OPEN, META_DOOR_OPEN, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE},
    {META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE},
    {META_TREE, META_FLOOR_DIRT, META_TREE, META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE, META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE},
    {META_TREE, META_FLOOR_DIRT, META_TREE, META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE, META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE},
    {META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE},
    {META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_CAMPFIRE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE},
    {META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE},
    {META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE},
    {META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE, META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE, META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE},
    {META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE, META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE, META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE},
    {META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE},
    {META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE},
    {META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE},
    {META_TREE, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_FLOOR_DIRT, META_TREE},
    {META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE, META_TREE}
};

static const MetatileId s_room_crypt_blueprint[ROOM_HEIGHT][ROOM_WIDTH] = {
    {META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_DOOR_LOCKED, META_DOOR_LOCKED, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP},
    {META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_CHEST_CLOSED, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_TORCH_LIT, META_FLOOR_STONE, META_FLOOR_STONE, META_PLATE_UP, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_PLATE_UP, META_FLOOR_STONE, META_FLOOR_STONE, META_TORCH_LIT, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_BLOCK, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_BLOCK, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_POT, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_POT, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_POT, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_POT, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE, META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE, META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE, META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE, META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_TORCH_LIT, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_TORCH_LIT, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_DOOR_OPEN, META_DOOR_OPEN, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP}
};

static const MetatileId s_room_aqueduct_blueprint[ROOM_HEIGHT][ROOM_WIDTH] = {
    {META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_DOOR_BOSS, META_DOOR_BOSS, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP},
    {META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_CHEST_CLOSED, META_FLOOR_STONE, META_SWITCH_OFF, META_FLOOR_STONE, META_TORCH_UNLIT, META_FLOOR_STONE, META_WATER, META_WATER, META_WATER, META_WATER, META_FLOOR_STONE, META_TORCH_UNLIT, META_FLOOR_STONE, META_FLOOR_STONE, META_CHEST_CLOSED, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WATER, META_WATER, META_WATER, META_WATER, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WATER, META_WATER, META_WATER, META_WATER, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_BRIDGE, META_BRIDGE, META_BRIDGE, META_BRIDGE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_BRIDGE, META_BRIDGE, META_BRIDGE, META_BRIDGE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WATER, META_WATER, META_WATER, META_WATER, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_CRACKED},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WATER, META_WATER, META_WATER, META_WATER, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WATER, META_WATER, META_WATER, META_WATER, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_TORCH_UNLIT, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WATER, META_WATER, META_WATER, META_WATER, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_TORCH_UNLIT, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WATER, META_WATER, META_WATER, META_WATER, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WATER, META_WATER, META_WATER, META_WATER, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_DOOR_OPEN, META_DOOR_OPEN, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP}
};

static const MetatileId s_room_sanctum_blueprint[ROOM_HEIGHT][ROOM_WIDTH] = {
    {META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP},
    {META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_BLOCK, META_FLOOR_STONE, META_FLOOR_STONE, META_TORCH_LIT, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_TORCH_LIT, META_FLOOR_STONE, META_FLOOR_STONE, META_BLOCK, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_BLOCK, META_FLOOR_STONE, META_FLOOR_STONE, META_TORCH_LIT, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_TORCH_LIT, META_FLOOR_STONE, META_FLOOR_STONE, META_BLOCK, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_DOOR_OPEN, META_DOOR_OPEN, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP}
};

static const MetatileId s_room_vault_blueprint[ROOM_HEIGHT][ROOM_WIDTH] = {
    {META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP},
    {META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_CHEST_CLOSED, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_CHEST_CLOSED, META_CHEST_CLOSED, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_CHEST_CLOSED, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_TORCH_LIT, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_TORCH_LIT, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_DOOR_OPEN, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_TORCH_LIT, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_TORCH_LIT, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_FACE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_FLOOR_STONE, META_WALL_FACE},
    {META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP, META_WALL_TOP}
};

static bool is_tile_solid(MetatileId t) {
    switch (t) {
        case META_WALL_TOP:
        case META_WALL_FACE:
        case META_WATER:
        case META_DOOR_LOCKED:
        case META_DOOR_BOSS:
        case META_WALL_CRACKED:
        case META_POT:
        case META_BLOCK:
        case META_TREE:
            return true;
        default:
            return false;
    }
}

static void spawn_actor(ActorType type, fixed_t x, fixed_t y, s8 hp, u8 extra) {
    for (int i = 0; i < MAX_ACTORS; i++) {
        if (!g_game.actors[i].active) {
            g_game.actors[i].type = type;
            g_game.actors[i].x = x;
            g_game.actors[i].y = y;
            g_game.actors[i].vx = 0;
            g_game.actors[i].vy = 0;
            g_game.actors[i].dir = DIR_DOWN;
            g_game.actors[i].hp = hp;
            g_game.actors[i].max_hp = hp;
            g_game.actors[i].state = 0;
            g_game.actors[i].timer = 0;
            g_game.actors[i].invuln_timer = 0;
            g_game.actors[i].extra = extra;
            g_game.actors[i].active = true;
            return;
        }
    }
}

static void spawn_projectile(ProjType type, fixed_t x, fixed_t y, fixed_t vx, fixed_t vy, Direction dir, u16 timer, u8 dmg) {
    for (int i = 0; i < MAX_PROJECTILES; i++) {
        if (!g_game.projectiles[i].active) {
            g_game.projectiles[i].type = type;
            g_game.projectiles[i].x = x;
            g_game.projectiles[i].y = y;
            g_game.projectiles[i].vx = vx;
            g_game.projectiles[i].vy = vy;
            g_game.projectiles[i].dir = dir;
            g_game.projectiles[i].timer = timer;
            g_game.projectiles[i].damage = dmg;
            g_game.projectiles[i].active = true;
            return;
        }
    }
}

static void spawn_pickup(PickupType type, fixed_t x, fixed_t y) {
    for (int i = 0; i < MAX_PICKUPS; i++) {
        if (!g_game.pickups[i].active) {
            g_game.pickups[i].type = type;
            g_game.pickups[i].x = x;
            g_game.pickups[i].y = y;
            g_game.pickups[i].timer = 600; // 10 seconds before despawn
            g_game.pickups[i].active = true;
            return;
        }
    }
}

void game_show_dialog(const char* l1, const char* l2, const char* l3) {
    g_game.dialog_lines[0] = l1;
    g_game.dialog_lines[1] = l2;
    g_game.dialog_lines[2] = l3;
    g_game.dialog_count = (l3 != NULL) ? 3 : ((l2 != NULL) ? 2 : 1);
    g_game.state = STATE_DIALOG;
}

void game_load_room(DungeonRoomId room_id, fixed_t spawn_x, fixed_t spawn_y) {
    g_game.current_room = room_id;
    g_game.player.x = spawn_x;
    g_game.player.y = spawn_y;
    g_game.player.vx = 0;
    g_game.player.vy = 0;

    // Clear actors, projectiles, pickups
    for (int i = 0; i < MAX_ACTORS; i++) g_game.actors[i].active = false;
    for (int i = 0; i < MAX_PROJECTILES; i++) g_game.projectiles[i].active = false;
    for (int i = 0; i < MAX_PICKUPS; i++) g_game.pickups[i].active = false;

    const MetatileId (*bp)[ROOM_WIDTH] = s_room_camp_blueprint;
    if (room_id == ROOM_CAMP) bp = s_room_camp_blueprint;
    else if (room_id == ROOM_UPPER_CRYPT) bp = s_room_crypt_blueprint;
    else if (room_id == ROOM_AQUEDUCT) bp = s_room_aqueduct_blueprint;
    else if (room_id == ROOM_SANCTUM) bp = s_room_sanctum_blueprint;
    else if (room_id == ROOM_SECRET_VAULT) bp = s_room_vault_blueprint;

    for (int r = 0; r < ROOM_HEIGHT; r++) {
        for (int c = 0; c < ROOM_WIDTH; c++) {
            g_game.room.tiles[r][c] = bp[r][c];
            graphics_set_metatile(c, r, bp[r][c]);
        }
    }

    // Set atmosphere, music, and spawns
    if (room_id == ROOM_CAMP) {
        audio_play_bgm(BGM_CAMP);
        graphics_set_blending(false, 0, 0);
        // Spawn NPC Merchant at campfire
        spawn_actor(ACTOR_NPC_MERCHANT, INT_TO_FP(10 * 16), INT_TO_FP(5 * 16), 1, 0);
    } else if (room_id == ROOM_UPPER_CRYPT) {
        audio_play_bgm(BGM_CRYPT);
        graphics_set_blending(true, 12, 4); // Soft crypt darkness
        // Spawn Skeletons and Slimes
        spawn_actor(ACTOR_SKELETON, INT_TO_FP(4 * 16), INT_TO_FP(8 * 16), 4, 0);
        spawn_actor(ACTOR_SKELETON, INT_TO_FP(15 * 16), INT_TO_FP(8 * 16), 4, 0);
        spawn_actor(ACTOR_SLIME, INT_TO_FP(8 * 16), INT_TO_FP(11 * 16), 2, 0);
        spawn_actor(ACTOR_SLIME, INT_TO_FP(12 * 16), INT_TO_FP(11 * 16), 2, 0);
        spawn_actor(ACTOR_BAT, INT_TO_FP(10 * 16), INT_TO_FP(4 * 16), 1, 0);
    } else if (room_id == ROOM_AQUEDUCT) {
        audio_play_bgm(BGM_CRYPT);
        graphics_set_blending(true, 10, 6);
        // Aqueduct monsters
        spawn_actor(ACTOR_SKELETON, INT_TO_FP(5 * 16), INT_TO_FP(11 * 16), 4, 0);
        spawn_actor(ACTOR_SKELETON, INT_TO_FP(14 * 16), INT_TO_FP(11 * 16), 4, 0);
        spawn_actor(ACTOR_BLADE_TRAP, INT_TO_FP(2 * 16), INT_TO_FP(6 * 16), 99, 0); // Horizontal trap
        spawn_actor(ACTOR_BAT, INT_TO_FP(16 * 16), INT_TO_FP(4 * 16), 1, 0);
    } else if (room_id == ROOM_SANCTUM) {
        audio_play_bgm(BGM_BOSS);
        graphics_set_blending(true, 14, 2);
        // Spawn Ancient Crypt Golem Boss (Body + 2 Fists)
        g_game.golem_phase = 1;
        g_game.golem_core_hp = 20;
        spawn_actor(ACTOR_GOLEM_BODY, INT_TO_FP(9 * 16 + 8), INT_TO_FP(3 * 16 + 8), 20, 0);
        spawn_actor(ACTOR_GOLEM_FIST, INT_TO_FP(6 * 16), INT_TO_FP(5 * 16), 5, 0); // Left fist
        spawn_actor(ACTOR_GOLEM_FIST, INT_TO_FP(13 * 16), INT_TO_FP(5 * 16), 5, 1); // Right fist
    } else if (room_id == ROOM_SECRET_VAULT) {
        audio_play_bgm(BGM_CAMP);
        graphics_set_blending(false, 0, 0);
        // Free health & treasure
        spawn_pickup(PICKUP_HEART_CONTAINER, INT_TO_FP(10 * 16), INT_TO_FP(6 * 16));
    }
}

void game_init(void) {
    g_game.state = STATE_TITLE;
    g_game.save_slot = 0;
    g_game.game_frame = 0;
    g_game.boss_defeated = false;

    // Initialize player default stats
    g_game.player.hearts = 6;      // 3 full hearts (6 half-hearts)
    g_game.player.max_hearts = 6;
    g_game.player.mp = 50;
    g_game.player.gold = 0;
    g_game.player.small_keys = 0;
    g_game.player.has_boss_key = false;
    g_game.player.unlocked_tools = (1 << TOOL_BOOMERANG) | (1 << TOOL_BOMB); // Boomerang & Bombs unlocked!
    g_game.player.active_tool = TOOL_BOOMERANG;
    g_game.player.state = PLAYER_IDLE;
    g_game.player.state_timer = 0;
    g_game.player.invuln_timer = 0;
    g_game.player.walk_frame = 0;
    g_game.player.anim_timer = 0;
    g_game.player.dir = DIR_UP;

    game_load_room(ROOM_CAMP, INT_TO_FP(10 * 16), INT_TO_FP(8 * 16));
}

static void update_player(void) {
    Player* p = &g_game.player;

    if (p->invuln_timer > 0) p->invuln_timer--;

    // Dodge Roll state
    if (p->state == PLAYER_ROLL) {
        p->state_timer--;
        fixed_t roll_spd = INT_TO_FP(3);
        if (p->dir == DIR_DOWN)  p->y += roll_spd;
        if (p->dir == DIR_UP)    p->y -= roll_spd;
        if (p->dir == DIR_LEFT)  p->x -= roll_spd;
        if (p->dir == DIR_RIGHT) p->x += roll_spd;

        if (p->state_timer == 0) {
            p->state = PLAYER_IDLE;
        }
        return;
    }

    // Sword Slash state
    if (p->state == PLAYER_SLASH) {
        p->state_timer--;
        if (p->state_timer == 0) {
            p->state = PLAYER_IDLE;
        }
        return;
    }

    // Quick-cycle Sub-Weapons with Button R or Select
    if (key_was_pressed(KEY_R) || key_was_pressed(KEY_SELECT)) {
        u8 cur = (u8)p->active_tool;
        for (int i = 1; i <= 3; i++) {
            u8 next = (cur + i) % 4;
            if (next != TOOL_NONE && (p->unlocked_tools & (1 << next))) {
                p->active_tool = (SubWeaponType)next;
                sfx_play_boomerang();
                break;
            }
        }
    }

    // Button L: Dodge Roll
    if (key_was_pressed(KEY_L)) {
        p->state = PLAYER_ROLL;
        p->state_timer = 18; // 18 frames of invulnerability
        p->invuln_timer = 20;
        sfx_play_dodge_roll();
        return;
    }

    // Button A: Sword Attack / Interact
    if (key_was_pressed(KEY_A)) {
        // Check if facing NPC
        fixed_t check_x = p->x + (p->dir == DIR_RIGHT ? INT_TO_FP(20) : (p->dir == DIR_LEFT ? -INT_TO_FP(20) : 0));
        fixed_t check_y = p->y + (p->dir == DIR_DOWN  ? INT_TO_FP(20) : (p->dir == DIR_UP   ? -INT_TO_FP(20) : 0));

        bool talked = false;
        for (int i = 0; i < MAX_ACTORS; i++) {
            if (g_game.actors[i].active && g_game.actors[i].type == ACTOR_NPC_MERCHANT) {
                fixed_t dx = check_x - g_game.actors[i].x;
                fixed_t dy = check_y - g_game.actors[i].y;
                if (dx > -INT_TO_FP(16) && dx < INT_TO_FP(16) && dy > -INT_TO_FP(16) && dy < INT_TO_FP(16)) {
                    p->hearts = p->max_hearts; // Campfire full heal!
                    sfx_play_heart_pickup();
                    game_show_dialog(
                        "CAMPFIRE REST: HEARTS RESTORED!",
                        "THE SUNKEN CRYPT LIES TO THE NORTH.",
                        "FIND BOMBS AND DEFEAT THE GOLEM!"
                    );
                    talked = true;
                    break;
                }
            }
        }

        // Check if facing Chest
        if (!talked) {
            u8 mx = (FP_TO_INT(check_x) + 8) / 16;
            u8 my = (FP_TO_INT(check_y) + 8) / 16;
            if (mx < ROOM_WIDTH && my < ROOM_HEIGHT) {
                if (g_game.room.tiles[my][mx] == META_CHEST_CLOSED) {
                    g_game.room.tiles[my][mx] = META_CHEST_OPEN;
                    graphics_set_metatile(mx, my, META_CHEST_OPEN);
                    sfx_play_chest_open();

                    if (g_game.current_room == ROOM_UPPER_CRYPT) {
                        p->unlocked_tools |= (1 << TOOL_BOOMERANG);
                        p->active_tool = TOOL_BOOMERANG;
                        game_show_dialog("FOUND THE STUN BOOMERANG!", "EQUIP WITH BUTTON B TO STUN FOES", "AND FLIP DISTANT CRYSTAL SWITCHES!");
                    } else if (g_game.current_room == ROOM_AQUEDUCT && mx < 10) {
                        p->unlocked_tools |= (1 << TOOL_FIRE_WAND);
                        p->active_tool = TOOL_FIRE_WAND;
                        game_show_dialog("FOUND THE FIRE WAND!", "PRESS B TO FIRE FLAME PROJECTILES", "AND IGNITE UNLIT TORCH SCONCES!");
                    } else if (g_game.current_room == ROOM_AQUEDUCT && mx >= 10) {
                        p->has_boss_key = true;
                        game_show_dialog("ACQUIRED BIG BOSS KEY!", "THE SANCTUM DOOR IS NOW UNLOCKED!", "PREPARE TO FACE THE CRYPT GOLEM!");
                    } else {
                        p->gold += 50;
                        game_show_dialog("FOUND 50 GOLD COINS!", "A VALUABLE RELIC OF THE CITADEL!", NULL);
                    }
                    talked = true;
                }
            }
        }

        if (!talked) {
            // Trigger Sword Slash!
            p->state = PLAYER_SLASH;
            p->state_timer = 12;
            sfx_play_sword_swing();

            fixed_t arc_x = p->x + (p->dir == DIR_RIGHT ? INT_TO_FP(16) : (p->dir == DIR_LEFT ? -INT_TO_FP(16) : 0));
            fixed_t arc_y = p->y + (p->dir == DIR_DOWN  ? INT_TO_FP(16) : (p->dir == DIR_UP   ? -INT_TO_FP(16) : 0));
            spawn_projectile(PROJ_SWORD_ARC, arc_x, arc_y, 0, 0, p->dir, 10, 2);
        }
        return;
    }

    // Button B: Use Sub-Weapon
    if (key_was_pressed(KEY_B)) {
        if (p->active_tool == TOOL_BOOMERANG) {
            sfx_play_boomerang();
            fixed_t vx = (p->dir == DIR_RIGHT) ? INT_TO_FP(3) : ((p->dir == DIR_LEFT) ? -INT_TO_FP(3) : 0);
            fixed_t vy = (p->dir == DIR_DOWN)  ? INT_TO_FP(3) : ((p->dir == DIR_UP)   ? -INT_TO_FP(3) : 0);
            spawn_projectile(PROJ_BOOMERANG, p->x, p->y, vx, vy, p->dir, 60, 1);
        } else if (p->active_tool == TOOL_BOMB) {
            sfx_play_bomb_drop();
            spawn_projectile(PROJ_BOMB, p->x, p->y, 0, 0, p->dir, 90, 6);
        } else if (p->active_tool == TOOL_FIRE_WAND) {
            sfx_play_fire_wand();
            fixed_t vx = (p->dir == DIR_RIGHT) ? INT_TO_FP(4) : ((p->dir == DIR_LEFT) ? -INT_TO_FP(4) : 0);
            fixed_t vy = (p->dir == DIR_DOWN)  ? INT_TO_FP(4) : ((p->dir == DIR_UP)   ? -INT_TO_FP(4) : 0);
            spawn_projectile(PROJ_FIREBALL, p->x, p->y, vx, vy, p->dir, 45, 3);
        }
    }

    // D-Pad Walk Movement
    fixed_t spd = INT_TO_FP(1) + (INT_TO_FP(1) / 2); // 1.5 px/frame
    fixed_t dx = 0;
    fixed_t dy = 0;

    if (key_is_down(KEY_LEFT))  { dx -= spd; p->dir = DIR_LEFT; }
    if (key_is_down(KEY_RIGHT)) { dx += spd; p->dir = DIR_RIGHT; }
    if (key_is_down(KEY_UP))    { dy -= spd; p->dir = DIR_UP; }
    if (key_is_down(KEY_DOWN))  { dy += spd; p->dir = DIR_DOWN; }

    if (dx != 0 || dy != 0) {
        p->state = PLAYER_WALK;
        p->anim_timer++;
        if (p->anim_timer >= 8) {
            p->anim_timer = 0;
            p->walk_frame ^= 1;
        }

        // Collision detection against dungeon tiles
        fixed_t new_x = p->x + dx;
        fixed_t new_y = p->y + dy;

        // Bounding box: 12x12 centered in 16x16 sprite
        s16 px = FP_TO_INT(new_x) + 8;
        s16 py = FP_TO_INT(new_y) + 8;

        u8 tile_x0 = (px - 6) / 16;
        u8 tile_x1 = (px + 6) / 16;
        u8 tile_y0 = (py - 6) / 16;
        u8 tile_y1 = (py + 6) / 16;

        bool collide_x = false;
        bool collide_y = false;

        if (tile_x0 < ROOM_WIDTH && tile_y0 < ROOM_HEIGHT && is_tile_solid(g_game.room.tiles[tile_y0][tile_x0])) collide_x = true;
        if (tile_x1 < ROOM_WIDTH && tile_y0 < ROOM_HEIGHT && is_tile_solid(g_game.room.tiles[tile_y0][tile_x1])) collide_x = true;
        if (tile_x0 < ROOM_WIDTH && tile_y1 < ROOM_HEIGHT && is_tile_solid(g_game.room.tiles[tile_y1][tile_x0])) collide_x = true;
        if (tile_x1 < ROOM_WIDTH && tile_y1 < ROOM_HEIGHT && is_tile_solid(g_game.room.tiles[tile_y1][tile_x1])) collide_x = true;

        if (!collide_x) p->x = new_x;
        if (!collide_y) p->y = new_y;

        // Doorway triggers & room transition checks
        if (p->y < INT_TO_FP(12) && (p->x >= INT_TO_FP(9 * 16) && p->x <= INT_TO_FP(11 * 16))) {
            // North exit
            if (g_game.current_room == ROOM_CAMP) {
                game_load_room(ROOM_UPPER_CRYPT, INT_TO_FP(10 * 16), INT_TO_FP(13 * 16));
            } else if (g_game.current_room == ROOM_UPPER_CRYPT) {
                game_load_room(ROOM_AQUEDUCT, INT_TO_FP(10 * 16), INT_TO_FP(13 * 16));
            } else if (g_game.current_room == ROOM_AQUEDUCT && g_game.player.has_boss_key) {
                game_load_room(ROOM_SANCTUM, INT_TO_FP(10 * 16), INT_TO_FP(13 * 16));
            }
        } else if (p->y > INT_TO_FP(14 * 16 - 4) && (p->x >= INT_TO_FP(9 * 16) && p->x <= INT_TO_FP(11 * 16))) {
            // South exit
            if (g_game.current_room == ROOM_UPPER_CRYPT) {
                game_load_room(ROOM_CAMP, INT_TO_FP(10 * 16), INT_TO_FP(2 * 16));
            } else if (g_game.current_room == ROOM_AQUEDUCT) {
                game_load_room(ROOM_UPPER_CRYPT, INT_TO_FP(10 * 16), INT_TO_FP(2 * 16));
            } else if (g_game.current_room == ROOM_SANCTUM) {
                game_load_room(ROOM_AQUEDUCT, INT_TO_FP(10 * 16), INT_TO_FP(2 * 16));
            }
        } else if (p->x > INT_TO_FP(19 * 16 - 8) && g_game.current_room == ROOM_AQUEDUCT) {
            // East cracked wall passage into Vault!
            game_load_room(ROOM_SECRET_VAULT, INT_TO_FP(1 * 16), INT_TO_FP(7 * 16));
        } else if (p->x < INT_TO_FP(8) && g_game.current_room == ROOM_SECRET_VAULT) {
            // West exit back to Aqueduct
            game_load_room(ROOM_AQUEDUCT, INT_TO_FP(18 * 16), INT_TO_FP(7 * 16));
        }
    } else {
        p->state = PLAYER_IDLE;
    }
}

static void update_actors(void) {
    for (int i = 0; i < MAX_ACTORS; i++) {
        Actor* a = &g_game.actors[i];
        if (!a->active) continue;

        if (a->invuln_timer > 0) a->invuln_timer--;

        a->timer++;

        // Slime: Bounces randomly, leaps towards player
        if (a->type == ACTOR_SLIME) {
            if (a->timer % 40 == 0) {
                a->vx = (g_game.player.x > a->x) ? INT_TO_FP(1) : -INT_TO_FP(1);
                a->vy = (g_game.player.y > a->y) ? INT_TO_FP(1) : -INT_TO_FP(1);
            } else if (a->timer % 40 == 20) {
                a->vx = 0;
                a->vy = 0;
            }
            a->x += a->vx;
            a->y += a->vy;
        }

        // Skeleton: Patrols and charges when player enters line of sight
        else if (a->type == ACTOR_SKELETON) {
            if (a->timer % 60 == 0) {
                fixed_t dx = g_game.player.x - a->x;
                fixed_t dy = g_game.player.y - a->y;
                if (dx > -INT_TO_FP(64) && dx < INT_TO_FP(64) && dy > -INT_TO_FP(64) && dy < INT_TO_FP(64)) {
                    a->vx = (dx > 0) ? (INT_TO_FP(1) + INT_TO_FP(1)/2) : -(INT_TO_FP(1) + INT_TO_FP(1)/2);
                    a->vy = (dy > 0) ? (INT_TO_FP(1) + INT_TO_FP(1)/2) : -(INT_TO_FP(1) + INT_TO_FP(1)/2);
                } else {
                    a->vx = (a->timer % 120 == 0) ? INT_TO_FP(1) : -INT_TO_FP(1);
                    a->vy = 0;
                }
            }
            a->x += a->vx;
            a->y += a->vy;
        }

        // Bat: Erratic fluttering
        else if (a->type == ACTOR_BAT) {
            a->vx = ((a->timer * 7) % 5 - 2) * (INT_TO_FP(1) / 2);
            a->vy = ((a->timer * 11) % 5 - 2) * (INT_TO_FP(1) / 2);
            a->x += a->vx;
            a->y += a->vy;
        }

        // Blade Trap: Surges across hallway
        else if (a->type == ACTOR_BLADE_TRAP) {
            if (a->state == 0) {
                // Dormant: check player alignment
                if (g_game.player.y >= a->y - INT_TO_FP(8) && g_game.player.y <= a->y + INT_TO_FP(8)) {
                    a->state = 1; // Surge!
                    a->vx = INT_TO_FP(4);
                    sfx_play_enemy_hit();
                }
            } else if (a->state == 1) {
                a->x += a->vx;
                if (a->x >= INT_TO_FP(17 * 16)) {
                    a->state = 2; // Retract slowly
                    a->vx = -INT_TO_FP(1);
                }
            } else if (a->state == 2) {
                a->x += a->vx;
                if (a->x <= INT_TO_FP(2 * 16)) {
                    a->state = 0;
                    a->vx = 0;
                }
            }
        }

        // Boss: Ancient Crypt Golem
        else if (a->type == ACTOR_GOLEM_BODY) {
            // Hover in arena center
            a->y += (a->timer & 16) ? (INT_TO_FP(1) / 4) : -(INT_TO_FP(1) / 4);

            // Phase 1 attacks
            if (g_game.golem_phase == 1) {
                if (a->timer % 120 == 60) {
                    // Ground pound: screen shake and ceiling stalactites!
                    graphics_trigger_shake(3, 15);
                    sfx_play_bomb_explode();
                    spawn_actor(ACTOR_STALACTITE, g_game.player.x, INT_TO_FP(16), 1, 0);
                }
                if (a->hp <= 10) {
                    // Core Overdrive trigger!
                    g_game.golem_phase = 2;
                    sfx_play_puzzle_solve();
                    graphics_trigger_shake(5, 30);
                }
            } else if (g_game.golem_phase == 2) {
                // Phase 2: Core Eye Laser Beam!
                if (a->timer % 90 == 30) {
                    sfx_play_fire_wand();
                    spawn_projectile(PROJ_GOLEM_LASER, a->x, a->y + INT_TO_FP(16), 0, INT_TO_FP(5), DIR_DOWN, 40, 2);
                }
            }
        }

        // Golem Fist: Orbits body or shoots rocket punch
        else if (a->type == ACTOR_GOLEM_FIST) {
            if (a->timer % 150 == 80) {
                // Rocket punch lunge!
                a->vx = (g_game.player.x > a->x) ? INT_TO_FP(3) : -INT_TO_FP(3);
                a->vy = (g_game.player.y > a->y) ? INT_TO_FP(3) : -INT_TO_FP(3);
                sfx_play_enemy_hit();
            } else if (a->timer % 150 == 130) {
                a->vx = 0;
                a->vy = 0;
            }
            a->x += a->vx;
            a->y += a->vy;
        }

        // Stalactite: Falls straight down and shatters
        else if (a->type == ACTOR_STALACTITE) {
            a->y += INT_TO_FP(4);
            if (a->y >= INT_TO_FP(14 * 16)) {
                sfx_play_enemy_hit();
                a->active = false;
            }
        }

        // Player collision with hostile actors
        if (a->type != ACTOR_NPC_MERCHANT && g_game.player.invuln_timer == 0 && g_game.player.state != PLAYER_ROLL) {
            fixed_t dx = g_game.player.x - a->x;
            fixed_t dy = g_game.player.y - a->y;
            if (dx > -INT_TO_FP(12) && dx < INT_TO_FP(12) && dy > -INT_TO_FP(12) && dy < INT_TO_FP(12)) {
                // Player hurt!
                if (g_game.player.hearts > 1) {
                    g_game.player.hearts--;
                    g_game.player.invuln_timer = 60;
                    graphics_trigger_shake(2, 8);
                    sfx_play_player_hurt();
                } else {
                    g_game.player.hearts = 0;
                    g_game.state = STATE_GAMEOVER;
                    sfx_play_player_hurt();
                }
            }
        }
    }
}

static void update_projectiles(void) {
    for (int i = 0; i < MAX_PROJECTILES; i++) {
        Projectile* p = &g_game.projectiles[i];
        if (!p->active) continue;

        p->timer--;
        if (p->timer == 0) {
            if (p->type == PROJ_BOMB) {
                // Detonate into explosion!
                p->type = PROJ_EXPLOSION;
                p->timer = 20;
                p->damage = 6;
                graphics_trigger_shake(4, 15);
                sfx_play_bomb_explode();

                // Check cracked walls in blast radius
                u8 mx = (FP_TO_INT(p->x) + 8) / 16;
                u8 my = (FP_TO_INT(p->y) + 8) / 16;
                for (int dy = -1; dy <= 1; dy++) {
                    for (int dx = -1; dx <= 1; dx++) {
                        int cx = mx + dx;
                        int cy = my + dy;
                        if (cx >= 0 && cx < ROOM_WIDTH && cy >= 0 && cy < ROOM_HEIGHT) {
                            if (g_game.room.tiles[cy][cx] == META_WALL_CRACKED) {
                                g_game.room.tiles[cy][cx] = META_DOOR_OPEN;
                                graphics_set_metatile(cx, cy, META_DOOR_OPEN);
                                sfx_play_door_unlock();
                            }
                        }
                    }
                }
            } else {
                p->active = false;
                continue;
            }
        }

        // Move projectile
        if (p->type == PROJ_BOOMERANG) {
            if (p->timer < 30) {
                // Return flight to player
                p->vx = (g_game.player.x > p->x) ? INT_TO_FP(3) : -INT_TO_FP(3);
                p->vy = (g_game.player.y > p->y) ? INT_TO_FP(3) : -INT_TO_FP(3);
            }
        }

        p->x += p->vx;
        p->y += p->vy;

        // Check torch sconces with Fireball
        if (p->type == PROJ_FIREBALL) {
            u8 mx = (FP_TO_INT(p->x) + 8) / 16;
            u8 my = (FP_TO_INT(p->y) + 8) / 16;
            if (mx < ROOM_WIDTH && my < ROOM_HEIGHT) {
                if (g_game.room.tiles[my][mx] == META_TORCH_UNLIT) {
                    g_game.room.tiles[my][mx] = META_TORCH_LIT;
                    graphics_set_metatile(mx, my, META_TORCH_LIT);
                    sfx_play_puzzle_solve();
                    p->active = false;
                }
            }
        }

        // Check crystal switch with Boomerang or Sword
        if (p->type == PROJ_BOOMERANG || p->type == PROJ_SWORD_ARC) {
            u8 mx = (FP_TO_INT(p->x) + 8) / 16;
            u8 my = (FP_TO_INT(p->y) + 8) / 16;
            if (mx < ROOM_WIDTH && my < ROOM_HEIGHT) {
                if (g_game.room.tiles[my][mx] == META_SWITCH_OFF) {
                    g_game.room.tiles[my][mx] = META_SWITCH_ON;
                    graphics_set_metatile(mx, my, META_SWITCH_ON);
                    sfx_play_puzzle_solve();
                }
            }
        }

        // Check collision against monsters
        for (int a = 0; a < MAX_ACTORS; a++) {
            Actor* act = &g_game.actors[a];
            if (!act->active || act->type == ACTOR_NPC_MERCHANT) continue;

            fixed_t dx = p->x - act->x;
            fixed_t dy = p->y - act->y;
            if (dx > -INT_TO_FP(16) && dx < INT_TO_FP(16) && dy > -INT_TO_FP(16) && dy < INT_TO_FP(16)) {
                // Hit enemy!
                if (act->invuln_timer == 0) {
                    act->hp -= p->damage;
                    act->invuln_timer = 15;
                    sfx_play_enemy_hit();

                    // Knockback
                    act->x += (p->vx > 0 ? INT_TO_FP(4) : -INT_TO_FP(4));
                    act->y += (p->vy > 0 ? INT_TO_FP(4) : -INT_TO_FP(4));

                    if (act->hp <= 0) {
                        act->active = false;
                        sfx_play_enemy_hit();
                        spawn_pickup(PICKUP_COIN, act->x, act->y);

                        // If Golem Boss slain!
                        if (act->type == ACTOR_GOLEM_BODY) {
                            g_game.boss_defeated = true;
                            audio_play_bgm(BGM_VICTORY);
                            graphics_trigger_shake(6, 60);
                            spawn_pickup(PICKUP_HEART_CONTAINER, act->x, act->y);
                            game_show_dialog(
                                "THE ANCIENT GOLEM HAS FALLEN!",
                                "THE SUNKEN CRYPT IS PURIFIED!",
                                "CLAIM THE HEART CONTAINER & REIGN!"
                            );
                        }
                    }

                    if (p->type != PROJ_EXPLOSION && p->type != PROJ_SWORD_ARC) {
                        p->active = false;
                        break;
                    }
                }
            }
        }
    }
}

static void update_pickups(void) {
    for (int i = 0; i < MAX_PICKUPS; i++) {
        Pickup* p = &g_game.pickups[i];
        if (!p->active) continue;

        p->timer--;
        if (p->timer == 0) {
            p->active = false;
            continue;
        }

        fixed_t dx = g_game.player.x - p->x;
        fixed_t dy = g_game.player.y - p->y;
        if (dx > -INT_TO_FP(12) && dx < INT_TO_FP(12) && dy > -INT_TO_FP(12) && dy < INT_TO_FP(12)) {
            // Collected!
            p->active = false;
            if (p->type == PICKUP_HEART) {
                if (g_game.player.hearts < g_game.player.max_hearts) g_game.player.hearts += 2;
                if (g_game.player.hearts > g_game.player.max_hearts) g_game.player.hearts = g_game.player.max_hearts;
                sfx_play_heart_pickup();
            } else if (p->type == PICKUP_COIN) {
                g_game.player.gold += 10;
                sfx_play_heart_pickup();
            } else if (p->type == PICKUP_HEART_CONTAINER) {
                g_game.player.max_hearts += 2;
                g_game.player.hearts = g_game.player.max_hearts;
                sfx_play_puzzle_solve();
                game_show_dialog("HEART CONTAINER ACQUIRED!", "YOUR MAXIMUM HEALTH INCREASED!", "REST AT THE CAMP TO PERSIST GAME.");
            }
        }
    }
}

void game_update(void) {
    g_game.game_frame++;
    audio_update();
    graphics_update_shake();

    if (g_game.state == STATE_TITLE) {
        if (key_was_pressed(KEY_START) || key_was_pressed(KEY_A)) {
            g_game.state = STATE_PLAY;
            sfx_play_sword_swing();
        }
        return;
    }

    if (g_game.state == STATE_DIALOG) {
        if (key_was_pressed(KEY_A) || key_was_pressed(KEY_B) || key_was_pressed(KEY_START)) {
            g_game.state = STATE_PLAY;
            graphics_clear_bg0();
        }
        return;
    }

    if (g_game.state == STATE_INVENTORY) {
        if (key_was_pressed(KEY_START) || key_was_pressed(KEY_B)) {
            g_game.state = STATE_PLAY;
            graphics_clear_bg0();
        }
        return;
    }

    if (g_game.state == STATE_GAMEOVER) {
        if (key_was_pressed(KEY_START) || key_was_pressed(KEY_A)) {
            // Revive at campfire!
            g_game.player.hearts = g_game.player.max_hearts;
            game_load_room(ROOM_CAMP, INT_TO_FP(10 * 16), INT_TO_FP(8 * 16));
            g_game.state = STATE_PLAY;
            graphics_clear_bg0();
        }
        return;
    }

    // Toggle Inventory with Start
    if (key_was_pressed(KEY_START)) {
        g_game.state = STATE_INVENTORY;
        return;
    }

    update_player();
    update_actors();
    update_projectiles();
    update_pickups();

    // Smooth camera tracking
    s16 target_cx = FP_TO_INT(g_game.player.x) - 120 + 8;
    s16 target_cy = FP_TO_INT(g_game.player.y) - 80 + 8;
    graphics_set_camera(target_cx, target_cy);
}

void game_draw(void) {
    graphics_oam_hide_all();

    if (g_game.state == STATE_TITLE) {
        graphics_clear_bg0();
        graphics_draw_box(3, 3, 24, 14, PAL_BG_UI);
        graphics_print_text(5, 5,  "AETHELGARD: CRYPT", PAL_BG_UI);
        graphics_print_text(5, 7,  "ACTION RPG FOR GBA", PAL_BG_UI);
        graphics_print_text(5, 10, "PRESS START / A", PAL_BG_UI);
        graphics_print_text(5, 12, "CONTROLS:", PAL_BG_UI);
        graphics_print_text(5, 13, "A: ATTACK  B: TOOL", PAL_BG_UI);
        graphics_print_text(5, 14, "L: ROLL    R: CYCLE", PAL_BG_UI);
        graphics_oam_copy();
        return;
    }

    if (g_game.state == STATE_INVENTORY) {
        graphics_draw_box(2, 2, 26, 16, PAL_BG_UI);
        graphics_print_text(4, 4,  "QUEST STATUS", PAL_BG_UI);
        graphics_print_text(4, 6,  "HEALTH:", PAL_BG_UI);
        graphics_print_num(12, 6,  g_game.player.hearts / 2, 2, PAL_BG_UI);
        graphics_print_text(15, 6, "/", PAL_BG_UI);
        graphics_print_num(17, 6,  g_game.player.max_hearts / 2, 2, PAL_BG_UI);
        graphics_print_text(4, 8,  "GOLD COINS:", PAL_BG_UI);
        graphics_print_num(16, 8,  g_game.player.gold, 3, PAL_BG_UI);
        graphics_print_text(4, 10, "TOOL: BOOMERANG", PAL_BG_UI);
        graphics_print_text(4, 12, "BOSS KEY: YES", PAL_BG_UI);
        graphics_print_text(4, 14, "PRESS B TO RESUME", PAL_BG_UI);
        graphics_oam_copy();
        return;
    }

    if (g_game.state == STATE_GAMEOVER) {
        graphics_draw_box(4, 5, 22, 10, PAL_BG_UI);
        graphics_print_text(7, 7,  "FALLEN IN BATTLE", PAL_BG_UI);
        graphics_print_text(6, 10, "PRESS START TO REVIVE", PAL_BG_UI);
        graphics_print_text(8, 12, "AT CAMPFIRE", PAL_BG_UI);
        graphics_oam_copy();
        return;
    }

    // Render HUD on BG0
    graphics_clear_bg0();

    // Hearts (Full / Half / Empty)
    u8 full_hearts = g_game.player.hearts / 2;
    bool has_half  = (g_game.player.hearts % 2) != 0;
    u8 total_heart_containers = g_game.player.max_hearts / 2;

    for (u8 h = 0; h < total_heart_containers; h++) {
        u16 tile = TILE_HEART_EMPTY;
        if (h < full_hearts) {
            tile = TILE_HEART_FULL;
        } else if (h == full_hearts && has_half) {
            tile = TILE_HEART_HALF;
        }
        graphics_set_bg0_tile(1 + h, 1, tile, PAL_BG_UI);
    }

    // Active tool display & Gold coins
    graphics_set_bg0_tile(21, 1, TILE_COIN_ICON, PAL_BG_UI);
    graphics_print_num(23, 1, g_game.player.gold, 3, PAL_BG_UI);

    // Dialog Box
    if (g_game.state == STATE_DIALOG) {
        graphics_draw_box(1, 12, 28, 7, PAL_BG_UI);
        for (int i = 0; i < g_game.dialog_count; i++) {
            if (g_game.dialog_lines[i]) {
                graphics_print_text(3, 14 + (i * 2), g_game.dialog_lines[i], PAL_BG_UI);
            }
        }
    }

    // Render Sprites
    u8 sprite_idx = 0;
    s16 cam_x = graphics_get_camera_x();
    s16 cam_y = graphics_get_camera_y();

    // 1. Draw Player Knight
    if (g_game.player.invuln_timer % 2 == 0) {
        s16 sx = FP_TO_INT(g_game.player.x) - cam_x;
        s16 sy = FP_TO_INT(g_game.player.y) - cam_y;

        u16 tile = SPRITE_KNIGHT_DOWN_0;
        bool hflip = false;

        if (g_game.player.state == PLAYER_ROLL) {
            tile = (g_game.player.state_timer & 4) ? SPRITE_KNIGHT_ROLL_1 : SPRITE_KNIGHT_ROLL_0;
        } else if (g_game.player.state == PLAYER_SLASH) {
            if (g_game.player.dir == DIR_DOWN)  tile = SPRITE_KNIGHT_SLASH_D;
            if (g_game.player.dir == DIR_UP)    tile = SPRITE_KNIGHT_SLASH_U;
            if (g_game.player.dir == DIR_LEFT)  { tile = SPRITE_KNIGHT_SLASH_S; hflip = true; }
            if (g_game.player.dir == DIR_RIGHT) tile = SPRITE_KNIGHT_SLASH_S;
        } else {
            if (g_game.player.dir == DIR_DOWN)  tile = g_game.player.walk_frame ? SPRITE_KNIGHT_DOWN_1 : SPRITE_KNIGHT_DOWN_0;
            if (g_game.player.dir == DIR_UP)    tile = g_game.player.walk_frame ? SPRITE_KNIGHT_UP_1 : SPRITE_KNIGHT_UP_0;
            if (g_game.player.dir == DIR_LEFT)  { tile = g_game.player.walk_frame ? SPRITE_KNIGHT_SIDE_1 : SPRITE_KNIGHT_SIDE_0; hflip = true; }
            if (g_game.player.dir == DIR_RIGHT) tile = g_game.player.walk_frame ? SPRITE_KNIGHT_SIDE_1 : SPRITE_KNIGHT_SIDE_0;
        }

        graphics_set_sprite(sprite_idx++, sx, sy, tile, 0, 1, PAL_OBJ_KNIGHT, hflip, false); // 16x16
    }

    // 2. Draw Actors
    for (int i = 0; i < MAX_ACTORS; i++) {
        Actor* a = &g_game.actors[i];
        if (!a->active) continue;

        s16 sx = FP_TO_INT(a->x) - cam_x;
        s16 sy = FP_TO_INT(a->y) - cam_y;

        if (a->type == ACTOR_SLIME) {
            u16 tile = (a->timer & 16) ? SPRITE_SLIME_1 : SPRITE_SLIME_0;
            graphics_set_sprite(sprite_idx++, sx, sy, tile, 0, 1, PAL_OBJ_MONSTER, false, false);
        } else if (a->type == ACTOR_SKELETON) {
            u16 tile = (a->timer & 16) ? SPRITE_SKELETON_D_1 : SPRITE_SKELETON_D_0;
            graphics_set_sprite(sprite_idx++, sx, sy, tile, 0, 1, PAL_OBJ_MONSTER, false, false);
        } else if (a->type == ACTOR_BAT) {
            u16 tile = (a->timer & 8) ? SPRITE_BAT_1 : SPRITE_BAT_0;
            graphics_set_sprite(sprite_idx++, sx, sy, tile, 0, 1, PAL_OBJ_MONSTER, false, false);
        } else if (a->type == ACTOR_BLADE_TRAP) {
            graphics_set_sprite(sprite_idx++, sx, sy, SPRITE_BLADE_TRAP, 0, 1, PAL_OBJ_MONSTER, false, false);
        } else if (a->type == ACTOR_GOLEM_BODY) {
            // Draw 32x32 Golem Body using 4 16x16 quadrants
            graphics_set_sprite(sprite_idx++, sx,      sy,      SPRITE_GOLEM_TL, 0, 1, PAL_OBJ_GOLEM, false, false);
            graphics_set_sprite(sprite_idx++, sx + 16, sy,      SPRITE_GOLEM_TR, 0, 1, PAL_OBJ_GOLEM, false, false);
            graphics_set_sprite(sprite_idx++, sx,      sy + 16, SPRITE_GOLEM_BL, 0, 1, PAL_OBJ_GOLEM, false, false);
            graphics_set_sprite(sprite_idx++, sx + 16, sy + 16, SPRITE_GOLEM_BR, 0, 1, PAL_OBJ_GOLEM, false, false);
            // Core eye
            graphics_set_sprite(sprite_idx++, sx + 8, sy + 8, SPRITE_GOLEM_CORE_EYE, 0, 1, PAL_OBJ_GOLEM, false, false);
        } else if (a->type == ACTOR_GOLEM_FIST) {
            graphics_set_sprite(sprite_idx++, sx, sy, SPRITE_GOLEM_FIST, 0, 1, PAL_OBJ_GOLEM, false, false);
        } else if (a->type == ACTOR_STALACTITE) {
            graphics_set_sprite(sprite_idx++, sx, sy, SPRITE_STALACTITE, 0, 1, PAL_OBJ_GOLEM, false, false);
        } else if (a->type == ACTOR_NPC_MERCHANT) {
            graphics_set_sprite(sprite_idx++, sx, sy, SPRITE_NPC_LOREKEEPER, 0, 1, PAL_OBJ_NPC, false, false);
        }
    }

    // 3. Draw Projectiles
    for (int i = 0; i < MAX_PROJECTILES; i++) {
        Projectile* p = &g_game.projectiles[i];
        if (!p->active) continue;

        s16 sx = FP_TO_INT(p->x) - cam_x;
        s16 sy = FP_TO_INT(p->y) - cam_y;

        if (p->type == PROJ_SWORD_ARC) {
            u16 tile = SPRITE_SWORD_ARC_D;
            if (p->dir == DIR_UP)    tile = SPRITE_SWORD_ARC_U;
            if (p->dir == DIR_LEFT || p->dir == DIR_RIGHT) tile = SPRITE_SWORD_ARC_S;
            graphics_set_sprite(sprite_idx++, sx, sy, tile, 0, 1, PAL_OBJ_KNIGHT, (p->dir == DIR_LEFT), false);
        } else if (p->type == PROJ_BOOMERANG) {
            u16 tile = (p->timer & 4) ? SPRITE_BOOMERANG_1 : SPRITE_BOOMERANG_0;
            graphics_set_sprite(sprite_idx++, sx, sy, tile, 0, 1, PAL_OBJ_FIRE_BOMB, false, false);
        } else if (p->type == PROJ_BOMB) {
            graphics_set_sprite(sprite_idx++, sx, sy, SPRITE_BOMB, 0, 1, PAL_OBJ_FIRE_BOMB, false, false);
        } else if (p->type == PROJ_EXPLOSION) {
            u16 tile = (p->timer > 12) ? SPRITE_EXPLOSION_0 : ((p->timer > 6) ? SPRITE_EXPLOSION_1 : SPRITE_EXPLOSION_2);
            graphics_set_sprite(sprite_idx++, sx, sy, tile, 0, 1, PAL_OBJ_FIRE_BOMB, false, false);
        } else if (p->type == PROJ_FIREBALL || p->type == PROJ_GOLEM_LASER) {
            u16 tile = (p->timer & 4) ? SPRITE_FIREBALL_1 : SPRITE_FIREBALL_0;
            graphics_set_sprite(sprite_idx++, sx, sy, tile, 0, 1, PAL_OBJ_FIRE_BOMB, false, false);
        }
    }

    // 4. Draw Pickups
    for (int i = 0; i < MAX_PICKUPS; i++) {
        Pickup* p = &g_game.pickups[i];
        if (!p->active) continue;

        s16 sx = FP_TO_INT(p->x) - cam_x;
        s16 sy = FP_TO_INT(p->y) - cam_y;

        u16 tile = SPRITE_HEART_PICKUP;
        if (p->type == PICKUP_COIN) tile = SPRITE_COIN_PICKUP;
        if (p->type == PICKUP_KEY) tile = SPRITE_KEY_PICKUP;
        if (p->type == PICKUP_BOSS_KEY) tile = SPRITE_BOSS_KEY_PICKUP;
        if (p->type == PICKUP_HEART_CONTAINER) tile = SPRITE_HEART_CONTAINER;

        graphics_set_sprite(sprite_idx++, sx, sy, tile, 0, 1, PAL_OBJ_ITEMS, false, false);
    }

    graphics_oam_copy();
}
